import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_component/Header";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Online Grocery App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <div>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
